/*
 * ============================================================
 *  多幸寿 ことばファイル（名前・セリフ・画面の文字。日本語と英語）
 * ============================================================
 *  ・ja が日本語、en が英語です。同じ名前（キー）の行を、両方そろえて書きかえます。
 *  ・{n} や {name} のような { } の部分には、ゲームが数字や名前を入れます。消さないでください。
 *  ・" " の中の文字だけを書きかえてください。
 *  ・セリフが | で区切ってあるものは、その中からランダムに1つが選ばれます。
 *  ・数値（値段・味など）は js/game/config.js にあります。
 * ============================================================
 */
(function (global) {
  'use strict';
  var OT = global.OT = global.OT || {};

  OT.TEXT = {
    ja: {
      // ---------- タイトル ----------
      'title.logo': 'Oh!Edo Taco Tuesday!!',
      'title.sub': '多幸寿',
      'title.tagline': '江戸の屋台で、タコスを売ろう。',
      'title.start': 'はじめる',
      'title.continue': 'つづきから（{day}日目）',
      'title.newgame': 'はじめから',
      'title.resetConfirm': 'セーブを消して、はじめからにしますか？',
      'title.by': '🦝 Tanuki Box',

      // ---------- 共通 ----------
      'ui.day': '{n}日目',
      'ui.money': '{n}文',
      'ui.rep': '評判 {n}',
      'ui.soundOn': '🔊 音あり',
      'ui.soundOff': '🔇 音なし',
      'ui.lang': 'English',
      'ui.ok': 'OK',
      'ui.yes': 'はい',
      'ui.no': 'いいえ',
      'ui.back': 'もどる',
      'ui.stock': '在庫 {n}',
      'ui.mon': '文',

      // ---------- 朝：仕入れ ----------
      'morning.title': '朝　仕入れ',
      'morning.lead': 'どこへ仕入れに行く？',
      'morning.left': '今日あと {n} か所（ミニゲーム）',
      'morning.soon': '近日公開',
      'morning.done': '今日はもう回れない',
      'morning.toNight': '仕込みを終えて夜の営業へ',
      'morning.stockTitle': 'いまの在庫',
      'morning.kind.game': 'ミニゲーム',
      'morning.kind.shop': '町の店',

      // ---------- 仕入れ先 ----------
      'sup.uogashi': '魚河岸',
      'sup.uogashi.desc': '朝の競り。鯛・鱚・蛸・鰹',
      'sup.ipponzuri': '江戸湾の一本釣り',
      'sup.ipponzuri.desc': '鯵・鰯・鮪・鰻',
      'sup.satoyama': '田んぼと里山',
      'sup.satoyama.desc': 'イナゴ・蜂の子・山椒・マコモダケ',
      'sup.yama': '山の追い込み',
      'sup.yama.desc': '猪・鹿',
      'sup.aomono': '青物市場',
      'sup.aomono.desc': '大根・葱・茗荷・胡瓜など',
      'sup.tofuya': '豆腐屋',
      'sup.tofuya.desc': '豆腐・油揚げ',
      'sup.toriya': '鳥屋',
      'sup.toriya.desc': '軍鶏・鴨・卵',
      'sup.momonjiya': 'ももんじや',
      'sup.momonjiya.desc': '猪・鹿（「薬」として）',
      'sup.yagenbori': '薬研堀',
      'sup.yagenbori.desc': '七味・唐辛子',
      'sup.komeya': '米屋',
      'sup.komeya.desc': '米・うどん粉・そば粉・海苔・酢',
      'sup.nagasaki': '長崎の抜け荷',
      'sup.nagasaki.desc': '夜の裏取引',

      // ---------- 魚河岸の競り ----------
      'auc.title': '魚河岸の競り',
      'auc.howto': '値札の数字は上がったり下がったり。安いと思ったらタップで競り落とそう！',
      'auc.start': '競りをはじめる',
      'auc.market': '相場 {n}文',
      'auc.portions': '{n}人前',
      'auc.tap': 'タップで買う！',
      'auc.won': '競り落とした！ {n}文',
      'auc.lost': 'ほかの店に取られた…',
      'auc.poor': 'お金が足りない！',
      'auc.cheap': '安い！',
      'auc.pricey': '高い…',
      'auc.timeLeft': 'のこり {n}秒',
      'auc.result': '競りの結果',
      'auc.none': '何も買わなかった',
      'auc.got': '{name} ×{n}人前（{price}文）',
      'auc.done': '仕入れ先を選ぶ画面へ',

      // ---------- 夜：営業 ----------
      'night.open': '開店！',
      'night.close': '閉店まで {n}秒',
      'night.closing': 'もうすぐ閉店',
      'night.closed': '閉店！',
      'night.tab.skin': '皮',
      'night.tab.main': '具',
      'night.tab.salsa': 'サルサ',
      'night.tab.herb': '薬味',
      'night.wrap': '包んで出す！',
      'night.clear': 'やり直す',
      'night.needSkin': 'まず「皮」を置こう',
      'night.full': 'もうのせられない',
      'night.out': '在庫がない！',
      'night.noGuest': 'お客さんを待とう',
      'night.pickGuest': '出す相手をタップで選べるよ',
      'night.order': '「{name}」ください！',
      'night.omakase': 'おまかせで！',
      'night.served': '{name}',
      'night.omakaseName': 'おまかせタコス',

      // ---------- 客 ----------
      'cust.chonin': '町人',
      'cust.shokunin': '職人',
      'cust.samurai': 'お侍',
      'cust.chonin.hello': 'ちょいと急いでんだ！|腹へった！はやいとこ頼むよ|へい、ごめんよ',
      'cust.shokunin.hello': '辛いやつ、あるかい？|仕事あがりだ、ひとつ頼む|ぴりっとしたのを頼むぜ',
      'cust.samurai.hello': 'ひとつ所望いたす|見目うるわしきものを頼む|縁起のよいものはあるか',
      'cust.chonin.3': 'はやい！うまい！こりゃいいや！|うんめえ！また来らぁ！',
      'cust.chonin.2': 'うん、悪かねえ|まあまあだな',
      'cust.chonin.1': 'なんでえこりゃ…|ちょいと違うなあ',
      'cust.shokunin.3': 'かーっ！効くねえ！|辛え！うめえ！最高だ！',
      'cust.shokunin.2': 'うまいが、もっと辛くてもいいぜ|悪くねえ',
      'cust.shokunin.1': 'こいつは物足りねえ…|頼んだのと違うぜ',
      'cust.samurai.3': 'なんと見事な…！感服いたした|紅白とはめでたい！',
      'cust.samurai.2': 'うむ、よい味である|悪くない',
      'cust.samurai.1': 'これは…所望したものではない|む…',
      'cust.angry': 'もう待てねえ！|遅い！帰る！|いつまで待たせるんだ！',

      // ---------- 結果 ----------
      'res.title': '{n}日目　本日の売上',
      'res.sales': '売上',
      'res.served': 'お客さん',
      'res.servedVal': '{n}人（怒って帰った人 {a}人）',
      'res.stars': '平均の星',
      'res.satisfaction': '満足度',
      'res.rep': '評判',
      'res.best': '看板タコス',
      'res.bestNone': '—',
      'res.money': '所持金',
      'res.share': '𝕏 でシェア',
      'res.next': '次の日へ',
      'share.text': '江戸の屋台「多幸寿」{day}日目の売上は{sales}文！看板は「{taco}」🌮 #OhEdoTacoTuesday #多幸寿',

      // ---------- ポン吉のひとこと ----------
      'pon.name': 'ポン吉',
      'pon.morning1': 'おはよう、マテオ！まずは魚河岸で魚を競り落とそう！',
      'pon.morningLow': 'トルティーヤが残り少ないよ…大事に使おうね',
      'pon.night1': 'お客さんの注文を見て、皮→具→サルサ→薬味の順にのせて「包んで出す」！',
      'pon.nightTip': '注文にない薬味を足すと、好みしだいで喜ばれるかも',

      // ---------- 食材 ----------
      'ing.tortilla': 'トルティーヤ',
      'ing.tai': '鯛',
      'ing.kisu_ten': '鱚の天ぷら',
      'ing.tako': '茹で蛸',
      'ing.katsuo': '鰹のたたき',
      'ing.shiraae': '白和え衣',
      'ing.sumiso': '酢味噌',
      'ing.bainiku': '梅肉',
      'ing.irizake': '煎り酒',
      'ing.daikon': '大根の千切り',
      'ing.kyuri': '胡瓜',
      'ing.myoga': '茗荷',
      'ing.negi': '葱',
      'ing.yuzu': '柚子',
      'ing.shichimi': '七味',

      // 競りの魚
      'fish.tai': '鯛',
      'fish.kisu': '鱚',
      'fish.tako': '蛸',
      'fish.katsuo': '鰹',

      // ---------- タコス ----------
      'taco.tempura': '江戸前天ぷらタコス',
      'taco.takotaco': '蛸のタコス',
      'taco.kohaku': '紅白めでタコス',
      // ---------- 第2段階 ----------
      'morning.lockedCh': '第{n}章で解禁',
      'pon.morning2': '町の店はミニゲームの数に入らないよ。足りないものは買い足そう',
      'pon.morning3': '同じタコスを出すほど熟練度が上がって、値段も上がるよ！',
      'pon.morning4': 'お客さんのひとこと感想は、好みのヒントだよ',
      'pon.morning5': '図鑑を見ると、まだ作っていないタコスがわかるよ',
      'pon.whale': '今日は鯨組の大物が競りに入るって！魚河岸へ急ごう！',
      'pon.noTortilla': 'トルティーヤが尽きちゃった…米屋の「もろこし粉の皮」で代わりにしよう',
      'pon.morokoshi': 'これ、江戸のトウモロコシの粉だって！でも灰汁で煮てないから、皮がぽろぽろ…。トルティーヤの代わりには使えるね',
      'rank.1': '名もなき屋台',
      'rank.2': '町の噂',
      'rank.3': '行列の屋台',
      'rank.4': '江戸の名物',
      'rank.5': '将軍の耳に届く',
      'rank.6': '献上',
      'rank.up': '評判ランク アップ！',
      'rank.unlocked': '新しく解禁：',
      'kago.title': 'かご蒸しタコス（作り置き）',
      'kago.desc': 'トルティーヤ（またはもろこし粉の皮）と里芋を{n}つずつ使って、{n}個蒸しておく。夜はタップ1回で出せる（星は2まで）',
      'kago.make': '{n}個蒸す',
      'kago.need': '皮と里芋が足りない',
      'shop.buy': '{price}文',
      'shop.poor': 'お金が足りない！',
      'shop.lot': '{n}人前',
      'shop.have': '在庫 {n}',
      'shop.leave': '仕入れ先を選ぶ画面へ',
      'shop.offSeason': '{season}だけ',
      'shop.lead.aomono': '朝どれの野菜がずらり。',
      'shop.lead.komeya': '米・粉・海苔・調味料。皮の材料はここで。',
      'shop.lead.tofuya': 'できたての豆腐と油揚げ。',
      'shop.lead.toriya': '軍鶏・鴨・卵。',
      'shop.lead.yagenbori': '七味の調合屋。辛さはここで決まる。',
      'shop.lead.momonjiya': '「薬をくだせえ」…猪と鹿は「薬」として売っている。',
      'season.spring': '春',
      'season.summer': '夏',
      'season.autumn': '秋',
      'season.winter': '冬',
      'auc.whale': '鯨組の大物だ！',
      'fish.uni': '雲丹',
      'fish.kujira': '鯨（鯨組の大物）',
      'fish.title': '江戸湾の一本釣り',
      'fish.howto': 'タップで糸を投げる。かかったら、押している間は糸を巻く。張りが赤くなったら指を離して！魚が暴れているときに巻くと糸が切れるよ。',
      'fish.start': '船を出す',
      'fish.tension': '張り',
      'fish.hooked': 'かかった！',
      'fish.nushi': 'ヌシだ！大鮪！',
      'fish.caught': '{name}を釣りあげた！',
      'fish.snap': '糸が切れた…',
      'fish.escape': '逃げられた…',
      'fish.tapCast': 'タップで糸を投げる',
      'fish.waiting': '……',
      'fish.surge': '暴れてる！離して！',
      'fish.hold': '押して巻く！',
      'fish.result': '釣りの結果',
      'fish.none': '坊主（1匹も釣れなかった）',
      'sea.aji': '鯵',
      'sea.iwashi': '鰯',
      'sea.maguro': '鮪',
      'sea.unagi': '鰻',
      'sea.nushi': 'ヌシの大鮪',
      'forage.title': '田んぼと里山の採集',
      'forage.howto': '跳ねるイナゴ、木の蜂の巣、あぜ道の山椒、水辺のマコモダケ。消える前にタップで捕ろう！',
      'forage.start': '里山へ行く',
      'forage.result': '採集の結果',
      'forage.none': '何もとれなかった',
      'dex.title': '図鑑',
      'dex.tab.tacos': 'タコス',
      'dex.tab.su': '素タコス',
      'dex.tab.ings': '食材',
      'dex.made': '{n}回',
      'dex.sudachi': 'すだち添え',
      'dex.lockedCh': '第{n}章で解禁',
      'dex.notYet': 'まだ作っていない',
      'dex.count': '{n} / {total}',
      'taste.hot': '辛',
      'taste.sour': '酸',
      'taste.umami': '旨',
      'taste.aroma': '香',
      'taste.texture': '食感',
      'night.levelUp': '{name} が Lv{lv} に！',
      'taco.su': '素タコス（{name}）',
      'taco.variant': '（{part}）',
      'part.rosu': 'ロース',
      'part.bara': 'バラ',
      'part.shita': '舌',
      'part.mimi': '耳',
      'cust.bozu': 'お坊さん',
      'cust.rikishi': '力士',
      'cust.tsujin': '通人',
      'cust.bozu.hello': '精進のものを、ひとつ|殺生のないものを頼みます|南無……おなかがすきました',
      'cust.rikishi.hello': 'ごっつぁんです！大盛りで！|腹ぺこでごわす|どすこい！いっぱいのせてくれ',
      'cust.tsujin.hello': '珍しいものはあるかね|さて、お手並み拝見|ありきたりの味は結構',
      'cust.bozu.3': 'ありがたや…身にしみます|見事な精進でございます',
      'cust.bozu.2': 'よいお味です|ありがたく',
      'cust.bozu.1': 'ふむ…|これは…',
      'cust.bozu.forbid': 'これは…殺生のものが入っております…|南無阿弥陀仏…これは食べられませぬ',
      'cust.rikishi.3': 'ごっつぁんです！最高でごわす！|うまい！もう一皿！',
      'cust.rikishi.2': '悪くないでごわす|うん、うまい',
      'cust.rikishi.1': 'ちと物足りんでごわす…|少ないでごわす',
      'cust.tsujin.3': '粋だねえ！こいつは参った|江戸にこんな味があったとは',
      'cust.tsujin.2': 'まあ、悪くはない|ふむ、及第点',
      'cust.tsujin.1': 'ありきたりだねえ|野暮だねえ',
      'cmt.more.0': 'もうちょい辛くてもいいな|ぴりっとしたのがほしいね',
      'cmt.more.1': 'さっぱりした酸っぱさがほしいな|柚子か梅が合いそうだ',
      'cmt.more.2': 'もっと旨みがほしいね|味がちょいと薄いかな',
      'cmt.more.3': '香りがもっとほしいね|薬味が恋しいな',
      'cmt.more.4': '歯ごたえがほしいな|しゃきっとしたのがほしいね',
      'cmt.less.0': '辛すぎる！|ひいっ、口が燃える',
      'cmt.less.1': 'ちょいと酸っぱいな|すっぱっ',
      'cmt.less.2': '味が濃すぎるね|ちょいとくどいな',
      'cmt.less.3': '香りが強すぎるね|薬味がちょいと多いな',
      'cmt.less.4': 'かみきれねえ|ちょいとかたいな',
      'cmt.great': 'また来るよ！|この味、忘れられねえ|明日も来る！',

      // 食材（第2段階）
      'ing.morokoshi': 'もろこし粉の皮',
      'ing.funoyaki': '麩の焼き',
      'ing.aburaage': '油揚げ',
      'ing.nori': '海苔',
      'ing.soba': 'そば粉の皮',
      'ing.usuyaki': '薄焼き卵',
      'ing.yakionigiri': '焼きおにぎり',
      'ing.aigawa': '藍染めの皮',
      'ing.kagomushi': 'かご蒸し',
      'ing.aji_nanban': '鯵の南蛮漬け',
      'ing.iwashi': '鰯',
      'ing.zuke': '鮪のづけ',
      'ing.akami': '鮪の赤身',
      'ing.chutoro': '中トロ',
      'ing.otoro': '大トロ',
      'ing.kabayaki': '鰻の蒲焼',
      'ing.uni': '生雲丹',
      'ing.kujira': '鯨の赤身と皮',
      'ing.inago': 'イナゴの佃煮',
      'ing.hachinoko': '蜂の子',
      'ing.makomo': '焼きマコモダケ',
      'ing.inoshishi': '猪（ロース）',
      'ing.ino_bara': '猪のバラ',
      'ing.ino_shita': '猪の舌',
      'ing.ino_mimi': '猪の耳',
      'ing.shika': '鹿（紅葉）',
      'ing.shamo': '軍鶏',
      'ing.kamo': '鴨',
      'ing.atsuyaki': '厚焼き玉子',
      'ing.tofu_soboro': '豆腐そぼろ',
      'ing.yakidofu': '焼き豆腐',
      'ing.nidaikon': '煮大根',
      'ing.konnyaku': '蒟蒻',
      'ing.satsumaimo': '薩摩芋',
      'ing.satoimo': '里芋',
      'ing.nasu': '焼き茄子',
      'ing.matsutake': '焼き松茸',
      'ing.sumeshi': '酢飯',
      'ing.shichimi_miso': '七味味噌',
      'ing.miso': '味噌',
      'ing.dengaku_miso': '田楽味噌',
      'ing.dashi': '出汁',
      'ing.oroshi': '大根おろし',
      'ing.amazu_myoga': '茗荷の甘酢漬け',
      'ing.shiraganegi': '白髪ねぎ',
      'ing.yakinegi': '焼き葱',
      'ing.shoga': '生姜',
      'ing.shiso': '紫蘇',
      'ing.mitsuba': '三つ葉',
      'ing.goma': '胡麻',
      'ing.kizaminori': '刻み海苔',
      'ing.wasabi': '山葵',
      'ing.sansho': '山椒',
      'ing.togarashi': '焼き唐辛子',

      // タコス（第2段階）
      'taco.katsuo_tataki': '鰹のたたきタコス',
      'taco.dorado': '油揚げドラード',
      'taco.shojin': '精進芋タコス',
      'taco.kago': 'かご蒸しタコス',
      'taco.nigiri': '握りタコス',
      'taco.kamo_nanban': '鴨南蛮タコス',
      'taco.nanbanzuke': '南蛮漬けタコス',
      'taco.oden': 'おでんビリア',
      'taco.chazuke': '〆の茶漬けタコス',
      'taco.tamago': '玉子タコス',
      'taco.sutaco': '素タコス（一文）',
      'taco.yamakujira': '山くじらパストール',
      'taco.shamo_tinga': '軍鶏チンガ',
      'taco.dengaku': '茄子田楽タコス',
      'taco.chapulines': 'イナゴのチャプリネス',
      'taco.escamoles': '蜂の子エスカモーレス',
      'taco.huitlacoche': '真菰茸ウィトラコチェ',
      'taco.adobada': '蒲焼アドバーダ',
      'taco.momiji': '紅葉アサーダ',
      'taco.botan': '牡丹ビリア',
      'taco.campechano': '江戸盛りカンペチャーノ',
      'taco.surtido': '猪スルティード',
      'taco.maguro3': '鮪三段',
      'taco.kozakana': '小魚三種盛り',
      'taco.matsutake': '松茸タコス',
      'taco.uni': '雲丹タコス',
      'taco.isana': '勇魚タコス',
      'taco.namiura': '浪裏タコス'
    },

    en: {
      'title.logo': 'Oh!Edo Taco Tuesday!!',
      'title.sub': 'TAKOSU',
      'title.tagline': 'Run a taco stall in old Edo.',
      'title.start': 'Start',
      'title.continue': 'Continue (Day {day})',
      'title.newgame': 'New game',
      'title.resetConfirm': 'Delete your save and start over?',
      'title.by': '🦝 Tanuki Box',

      'ui.day': 'Day {n}',
      'ui.money': '{n} mon',
      'ui.rep': 'Rep {n}',
      'ui.soundOn': '🔊 Sound on',
      'ui.soundOff': '🔇 Sound off',
      'ui.lang': '日本語',
      'ui.ok': 'OK',
      'ui.yes': 'Yes',
      'ui.no': 'No',
      'ui.back': 'Back',
      'ui.stock': 'x{n}',
      'ui.mon': 'mon',

      'morning.title': 'Morning: Shopping',
      'morning.lead': 'Where will you shop today?',
      'morning.left': '{n} more trips today (mini-games)',
      'morning.soon': 'Coming soon',
      'morning.done': 'No more trips today',
      'morning.toNight': 'Finish prep and open for the night',
      'morning.stockTitle': 'Pantry',
      'morning.kind.game': 'Mini-game',
      'morning.kind.shop': 'Shop',

      'sup.uogashi': 'Fish Market',
      'sup.uogashi.desc': 'Morning auction: sea bream, whiting, octopus, bonito',
      'sup.ipponzuri': 'Edo Bay Fishing',
      'sup.ipponzuri.desc': 'Horse mackerel, sardine, tuna, eel',
      'sup.satoyama': 'Paddies & Hills',
      'sup.satoyama.desc': 'Locusts, bee larvae, sansho, water bamboo',
      'sup.yama': 'Mountain Drive',
      'sup.yama.desc': 'Boar, deer',
      'sup.aomono': 'Green Market',
      'sup.aomono.desc': 'Daikon, scallion, myoga, cucumber…',
      'sup.tofuya': 'Tofu Shop',
      'sup.tofuya.desc': 'Tofu, fried tofu',
      'sup.toriya': 'Poultry Shop',
      'sup.toriya.desc': 'Gamecock, duck, eggs',
      'sup.momonjiya': 'Momonjiya',
      'sup.momonjiya.desc': 'Boar and deer (sold as "medicine")',
      'sup.yagenbori': 'Yagenbori Spices',
      'sup.yagenbori.desc': 'Shichimi, chili',
      'sup.komeya': 'Rice Shop',
      'sup.komeya.desc': 'Rice, wheat & buckwheat flour, nori, vinegar',
      'sup.nagasaki': 'Nagasaki Smugglers',
      'sup.nagasaki.desc': 'Secret night deals',

      'auc.title': 'Fish Market Auction',
      'auc.howto': 'The price tag goes up and down. Tap when it looks cheap to win the bid!',
      'auc.start': 'Start the auction',
      'auc.market': 'Usual {n} mon',
      'auc.portions': '{n} servings',
      'auc.tap': 'Tap to bid!',
      'auc.won': 'Sold to you! {n} mon',
      'auc.lost': 'Another buyer got it…',
      'auc.poor': 'Not enough money!',
      'auc.cheap': 'Cheap!',
      'auc.pricey': 'Pricey…',
      'auc.timeLeft': '{n}s left',
      'auc.result': 'Auction results',
      'auc.none': 'You bought nothing',
      'auc.got': '{name} x{n} servings ({price} mon)',
      'auc.done': 'Back to the map',

      'night.open': 'Open!',
      'night.close': 'Closing in {n}s',
      'night.closing': 'Last orders',
      'night.closed': 'Closed!',
      'night.tab.skin': 'Shell',
      'night.tab.main': 'Filling',
      'night.tab.salsa': 'Salsa',
      'night.tab.herb': 'Garnish',
      'night.wrap': 'Wrap & serve!',
      'night.clear': 'Start over',
      'night.needSkin': 'Lay down a shell first',
      'night.full': 'No room for more',
      'night.out': 'Out of stock!',
      'night.noGuest': 'Wait for a customer',
      'night.pickGuest': 'Tap a customer to choose who gets it',
      'night.order': '"{name}", please!',
      'night.omakase': "Chef's choice!",
      'night.served': '{name}',
      'night.omakaseName': "Chef's Choice Taco",

      'cust.chonin': 'Townsman',
      'cust.shokunin': 'Craftsman',
      'cust.samurai': 'Samurai',
      'cust.chonin.hello': "I'm in a hurry!|Starving! Quick, please|Hey there!",
      'cust.shokunin.hello': 'Got anything spicy?|Done with work. One, please|Something with a kick!',
      'cust.samurai.hello': 'I shall have one.|Something pleasing to the eye.|Anything auspicious?',
      'cust.chonin.3': "Fast and tasty! Love it!|Delicious! I'll be back!",
      'cust.chonin.2': 'Not bad.|Pretty good.',
      'cust.chonin.1': "What's this…|Not quite right.",
      'cust.shokunin.3': 'Whoa, that kick! Perfect!|Hot! Tasty! The best!',
      'cust.shokunin.2': 'Good, but it could be hotter.|Not bad.',
      'cust.shokunin.1': "Needs more punch…|That's not what I ordered.",
      'cust.samurai.3': 'Magnificent! I am impressed.|Red and white — how auspicious!',
      'cust.samurai.2': 'A fine flavor.|Not bad.',
      'cust.samurai.1': 'This is not what I asked for.|Hmm…',
      'cust.angry': "I can't wait any longer!|Too slow! I'm leaving!|How long will this take?!",

      'res.title': 'Day {n}: Tonight’s takings',
      'res.sales': 'Sales',
      'res.served': 'Customers',
      'res.servedVal': '{n} (left angry: {a})',
      'res.stars': 'Average stars',
      'res.satisfaction': 'Satisfaction',
      'res.rep': 'Reputation',
      'res.best': 'Best seller',
      'res.bestNone': '—',
      'res.money': 'Purse',
      'res.share': 'Share on 𝕏',
      'res.next': 'Next day',
      'share.text': 'My Edo taco stall "Takosu" made {sales} mon on day {day}! Best seller: "{taco}" 🌮 #OhEdoTacoTuesday',

      'pon.name': 'Ponkichi',
      'pon.morning1': 'Morning, Mateo! Let’s win some fish at the market auction!',
      'pon.morningLow': 'We’re running low on tortillas… use them wisely!',
      'pon.night1': 'Read the order, then add shell → filling → salsa → garnish and tap “Wrap & serve”!',
      'pon.nightTip': 'Extra garnish might make them happier — if it suits their taste.',

      'ing.tortilla': 'Tortilla',
      'ing.tai': 'Sea bream',
      'ing.kisu_ten': 'Whiting tempura',
      'ing.tako': 'Boiled octopus',
      'ing.katsuo': 'Seared bonito',
      'ing.shiraae': 'Tofu cream',
      'ing.sumiso': 'Vinegar miso',
      'ing.bainiku': 'Plum paste',
      'ing.irizake': 'Irizake sauce',
      'ing.daikon': 'Shredded daikon',
      'ing.kyuri': 'Cucumber',
      'ing.myoga': 'Myoga ginger',
      'ing.negi': 'Scallion',
      'ing.yuzu': 'Yuzu',
      'ing.shichimi': 'Shichimi',

      'fish.tai': 'Sea bream',
      'fish.kisu': 'Whiting',
      'fish.tako': 'Octopus',
      'fish.katsuo': 'Bonito',

      'taco.tempura': 'Edo Tempura Taco',
      'taco.takotaco': 'Octopus Taco',
      'taco.kohaku': 'Red & White Lucky Taco',
      'morning.lockedCh': 'Unlocks in chapter {n}',
      'pon.morning2': "Shops don't count toward today's trips. Stock up on what you're missing!",
      'pon.morning3': 'The more you serve a taco, the higher its mastery — and its price!',
      'pon.morning4': "Customers' little comments are hints about their taste.",
      'pon.morning5': "Check the Taco Book to see what you haven't made yet.",
      'pon.whale': "A whaling crew's big catch is at the auction today! Hurry to the fish market!",
      'pon.noTortilla': "We're out of tortillas… let's use the Rice Shop's corn-flour shells instead.",
      'pon.morokoshi': "This is Edo's own corn flour! But it wasn't cooked in lye, so the shells crumble… It'll work in place of tortillas, though.",
      'rank.1': 'Nameless Stall',
      'rank.2': 'Talk of the Town',
      'rank.3': 'Stall with a Line',
      'rank.4': 'Pride of Edo',
      'rank.5': "Heard in the Shogun's Castle",
      'rank.6': 'The Offering',
      'rank.up': 'Reputation rank up!',
      'rank.unlocked': 'New unlocks:',
      'kago.title': 'Basket Tacos (made ahead)',
      'kago.desc': 'Use {n} shells (tortilla or corn-flour) and {n} taro to steam {n} tacos. At night, serve with one tap (max 2 stars).',
      'kago.make': 'Steam {n}',
      'kago.need': 'Not enough shells or taro',
      'shop.buy': '{price} mon',
      'shop.poor': 'Not enough money!',
      'shop.lot': '{n} servings',
      'shop.have': 'Have {n}',
      'shop.leave': 'Back to the map',
      'shop.offSeason': '{season} only',
      'shop.lead.aomono': 'Fresh vegetables picked this morning.',
      'shop.lead.komeya': 'Rice, flour, nori and seasonings. Shell ingredients are here.',
      'shop.lead.tofuya': 'Fresh tofu and fried tofu.',
      'shop.lead.toriya': 'Gamecock, duck and eggs.',
      'shop.lead.yagenbori': 'The shichimi blender. Heat is decided here.',
      'shop.lead.momonjiya': '"Some medicine, please…" Boar and deer are sold as "medicine".',
      'season.spring': 'Spring',
      'season.summer': 'Summer',
      'season.autumn': 'Autumn',
      'season.winter': 'Winter',
      'auc.whale': "The whaling crew's big catch!",
      'fish.uni': 'Sea urchin',
      'fish.kujira': 'Whale (big catch)',
      'fish.title': 'Edo Bay Fishing',
      'fish.howto': 'Tap to cast. Once hooked, hold to reel in. When the tension turns red, let go! Reeling while the fish thrashes will snap the line.',
      'fish.start': 'Set out',
      'fish.tension': 'Tension',
      'fish.hooked': 'Hooked!',
      'fish.nushi': 'The Lord of the Bay! A giant tuna!',
      'fish.caught': 'Caught a {name}!',
      'fish.snap': 'The line snapped…',
      'fish.escape': 'It got away…',
      'fish.tapCast': 'Tap to cast',
      'fish.waiting': '…',
      'fish.surge': "It's thrashing! Let go!",
      'fish.hold': 'Hold to reel!',
      'fish.result': 'Fishing results',
      'fish.none': 'Not a single bite',
      'sea.aji': 'Horse mackerel',
      'sea.iwashi': 'Sardine',
      'sea.maguro': 'Tuna',
      'sea.unagi': 'Eel',
      'sea.nushi': 'Giant tuna (the Lord)',
      'forage.title': 'Paddies & Hills',
      'forage.howto': 'Hopping locusts, beehives in the trees, sansho by the path, water bamboo by the water. Tap them before they vanish!',
      'forage.start': 'Head to the hills',
      'forage.result': 'Foraging results',
      'forage.none': 'You found nothing',
      'dex.title': 'Taco Book',
      'dex.tab.tacos': 'Tacos',
      'dex.tab.su': 'Simple',
      'dex.tab.ings': 'Ingredients',
      'dex.made': 'x{n}',
      'dex.sudachi': 'With sudachi',
      'dex.lockedCh': 'Unlocks in chapter {n}',
      'dex.notYet': 'Not made yet',
      'dex.count': '{n} / {total}',
      'taste.hot': 'Hot',
      'taste.sour': 'Sour',
      'taste.umami': 'Umami',
      'taste.aroma': 'Aroma',
      'taste.texture': 'Crunch',
      'night.levelUp': '{name} reached Lv{lv}!',
      'taco.su': 'Simple Taco ({name})',
      'taco.variant': ' ({part})',
      'part.rosu': 'loin',
      'part.bara': 'belly',
      'part.shita': 'tongue',
      'part.mimi': 'ear',
      'cust.bozu': 'Monk',
      'cust.rikishi': 'Sumo',
      'cust.tsujin': 'Gourmet',
      'cust.bozu.hello': 'Something without meat, please.|Nothing that took a life, please.|Namu… I am hungry.',
      'cust.rikishi.hello': 'A big one, please!|I am starving!|Pile it high!',
      'cust.tsujin.hello': 'Anything unusual?|Let us see what you can do.|Nothing ordinary, thank you.',
      'cust.bozu.3': 'What a blessing…|A splendid vegetarian dish.',
      'cust.bozu.2': 'A fine flavor.|Thank you kindly.',
      'cust.bozu.1': 'Hmm…|This is…',
      'cust.bozu.forbid': 'This contains meat or fish…|Namu Amida Butsu… I cannot eat this.',
      'cust.rikishi.3': 'Magnificent! Another plate!|Delicious! One more!',
      'cust.rikishi.2': 'Not bad at all.|Tasty.',
      'cust.rikishi.1': 'A bit small…|Not enough…',
      'cust.tsujin.3': 'How stylish! I am beaten.|Who knew Edo had such flavors?',
      'cust.tsujin.2': 'Not bad, I suppose.|A passing grade.',
      'cust.tsujin.1': 'How ordinary.|How unrefined.',
      'cmt.more.0': 'Could be spicier.|I want more kick.',
      'cmt.more.1': 'A bit of sourness would be nice.|Yuzu or plum would suit this.',
      'cmt.more.2': 'Needs more savory depth.|A little bland.',
      'cmt.more.3': 'I want more aroma.|Missing some garnish.',
      'cmt.more.4': 'I want some crunch.|Something crisp would be nice.',
      'cmt.less.0': 'Too hot!|My mouth is on fire!',
      'cmt.less.1': 'A bit too sour.|So sour!',
      'cmt.less.2': 'Too rich.|A bit heavy.',
      'cmt.less.3': 'Too much aroma.|A lot of garnish.',
      'cmt.less.4': "I can't chew this.|A bit tough.",
      'cmt.great': "I'll be back!|I won't forget this taste!|See you tomorrow!",

      'ing.morokoshi': 'Corn-flour shell',
      'ing.funoyaki': 'Fu-no-yaki crepe',
      'ing.aburaage': 'Fried tofu pouch',
      'ing.nori': 'Nori sheet',
      'ing.soba': 'Buckwheat crepe',
      'ing.usuyaki': 'Egg crepe',
      'ing.yakionigiri': 'Grilled rice ball',
      'ing.aigawa': 'Indigo shell',
      'ing.kagomushi': 'Basket taco',
      'ing.aji_nanban': 'Nanban mackerel',
      'ing.iwashi': 'Sardine',
      'ing.zuke': 'Marinated tuna',
      'ing.akami': 'Lean tuna',
      'ing.chutoro': 'Medium-fatty tuna',
      'ing.otoro': 'Fatty tuna',
      'ing.kabayaki': 'Grilled eel',
      'ing.uni': 'Sea urchin',
      'ing.kujira': 'Whale meat',
      'ing.inago': 'Candied locusts',
      'ing.hachinoko': 'Bee larvae',
      'ing.makomo': 'Grilled water bamboo',
      'ing.inoshishi': 'Boar (loin)',
      'ing.ino_bara': 'Boar belly',
      'ing.ino_shita': 'Boar tongue',
      'ing.ino_mimi': 'Boar ear',
      'ing.shika': 'Venison',
      'ing.shamo': 'Gamecock',
      'ing.kamo': 'Duck',
      'ing.atsuyaki': 'Rolled omelet',
      'ing.tofu_soboro': 'Tofu crumble',
      'ing.yakidofu': 'Grilled tofu',
      'ing.nidaikon': 'Simmered daikon',
      'ing.konnyaku': 'Konnyaku',
      'ing.satsumaimo': 'Sweet potato',
      'ing.satoimo': 'Taro',
      'ing.nasu': 'Grilled eggplant',
      'ing.matsutake': 'Grilled matsutake',
      'ing.sumeshi': 'Sushi rice',
      'ing.shichimi_miso': 'Shichimi miso',
      'ing.miso': 'Miso',
      'ing.dengaku_miso': 'Sweet dengaku miso',
      'ing.dashi': 'Dashi broth',
      'ing.oroshi': 'Grated daikon',
      'ing.amazu_myoga': 'Pickled myoga',
      'ing.shiraganegi': 'Shredded scallion',
      'ing.yakinegi': 'Grilled scallion',
      'ing.shoga': 'Ginger',
      'ing.shiso': 'Shiso leaf',
      'ing.mitsuba': 'Mitsuba',
      'ing.goma': 'Sesame',
      'ing.kizaminori': 'Shredded nori',
      'ing.wasabi': 'Wasabi',
      'ing.sansho': 'Sansho pepper',
      'ing.togarashi': 'Roasted chili',

      'taco.katsuo_tataki': 'Seared Bonito Taco',
      'taco.dorado': 'Aburaage Dorado',
      'taco.shojin': 'Shojin Imo Taco',
      'taco.kago': 'Seiro Basket Taco',
      'taco.nigiri': 'Nigiri Taco',
      'taco.kamo_nanban': 'Kamo Nanban Taco',
      'taco.nanbanzuke': 'Nanbanzuke Taco',
      'taco.oden': 'Oden Birria',
      'taco.chazuke': 'Last-Call Chazuke Taco',
      'taco.tamago': 'Tamago Taco',
      'taco.sutaco': 'Plain Taco (1 mon)',
      'taco.yamakujira': 'Yama-Kujira Pastor',
      'taco.shamo_tinga': 'Shamo Tinga',
      'taco.dengaku': 'Dengaku Taco',
      'taco.chapulines': 'Inago Chapulines',
      'taco.escamoles': 'Hachinoko Escamoles',
      'taco.huitlacoche': 'Makomo Huitlacoche',
      'taco.adobada': 'Kabayaki Adobada',
      'taco.momiji': 'Momiji Asada',
      'taco.botan': 'Botan Birria',
      'taco.campechano': 'Edo Campechano',
      'taco.surtido': 'Boar Surtido',
      'taco.maguro3': 'Maguro Three Ways',
      'taco.kozakana': 'Small Fry Trio',
      'taco.matsutake': 'Matsutake Taco',
      'taco.uni': 'Uni Taco',
      'taco.isana': 'Isana Whale Taco',
      'taco.namiura': 'Great Wave Taco'
    }
  };
})(window);
