/*
 * ============================================================
 *  多幸寿 ことばファイル（名前・セリフ・画面の文字。日本語と英語）
 * ============================================================
 *  ・ja が日本語、en が英語です。同じ名前（キー）の行を、両方そろえて書きかえます。
 *  ・{n} や {name} のような { } の部分には、ゲームが数字や名前を入れます。消さないでください。
 *  ・" " の中の文字だけを書きかえてください。
 *  ・セリフが | で区切ってあるものは、その中からランダムに1つが選ばれます。
 *  ・数値（値段・味など）は js/game/config.js にあります。
 * ============================================================
 */
(function (global) {
  'use strict';
  var OT = global.OT = global.OT || {};

  OT.TEXT = {
    ja: {
      // ---------- タイトル ----------
      'title.logo': 'Oh!Edo Taco Tuesday!!',
      'title.sub': '多幸寿',
      'title.tagline': '江戸の屋台で、タコスを売ろう。',
      'title.start': 'はじめる',
      'title.continue': 'つづきから（{day}日目）',
      'title.newgame': 'はじめから',
      'title.resetConfirm': 'セーブを消して、はじめからにしますか？',
      'title.by': '🦝 Tanuki Box',

      // ---------- 共通 ----------
      'ui.day': '{n}日目',
      'ui.money': '{n}文',
      'ui.rep': '評判 {n}',
      'ui.soundOn': '🔊 音あり',
      'ui.soundOff': '🔇 音なし',
      'ui.lang': 'English',
      'ui.ok': 'OK',
      'ui.yes': 'はい',
      'ui.no': 'いいえ',
      'ui.back': 'もどる',
      'ui.stock': '在庫 {n}',
      'ui.mon': '文',

      // ---------- 朝：仕入れ ----------
      'morning.title': '朝　仕入れ',
      'morning.lead': 'どこへ仕入れに行く？',
      'morning.left': '今日あと {n} か所（ミニゲーム）',
      'morning.soon': '近日公開',
      'morning.done': '今日はもう回れない',
      'morning.toNight': '仕込みを終えて夜の営業へ',
      'morning.stockTitle': 'いまの在庫',
      'morning.kind.game': 'ミニゲーム',
      'morning.kind.shop': '町の店',

      // ---------- 仕入れ先 ----------
      'sup.uogashi': '魚河岸',
      'sup.uogashi.desc': '朝の競り。鯛・鱚・蛸・鰹',
      'sup.ipponzuri': '江戸湾の一本釣り',
      'sup.ipponzuri.desc': '鯵・鰯・鮪・鰻',
      'sup.satoyama': '田んぼと里山',
      'sup.satoyama.desc': 'イナゴ・蜂の子・山椒・マコモダケ',
      'sup.yama': '山の追い込み',
      'sup.yama.desc': '猪・鹿',
      'sup.aomono': '青物市場',
      'sup.aomono.desc': '大根・葱・茗荷・胡瓜など',
      'sup.tofuya': '豆腐屋',
      'sup.tofuya.desc': '豆腐・油揚げ',
      'sup.toriya': '鳥屋',
      'sup.toriya.desc': '軍鶏・鴨・卵',
      'sup.momonjiya': 'ももんじや',
      'sup.momonjiya.desc': '猪・鹿（「薬」として）',
      'sup.yagenbori': '薬研堀',
      'sup.yagenbori.desc': '七味・唐辛子',
      'sup.komeya': '米屋',
      'sup.komeya.desc': '米・うどん粉・そば粉・海苔・酢',
      'sup.nagasaki': '長崎の抜け荷',
      'sup.nagasaki.desc': '夜の裏取引',

      // ---------- 魚河岸の競り ----------
      'auc.title': '魚河岸の競り',
      'auc.howto': '値札の数字は上がったり下がったり。安いと思ったらタップで競り落とそう！',
      'auc.start': '競りをはじめる',
      'auc.market': '相場 {n}文',
      'auc.portions': '{n}人前',
      'auc.tap': 'タップで買う！',
      'auc.won': '競り落とした！ {n}文',
      'auc.lost': 'ほかの店に取られた…',
      'auc.poor': 'お金が足りない！',
      'auc.cheap': '安い！',
      'auc.pricey': '高い…',
      'auc.timeLeft': 'のこり {n}秒',
      'auc.result': '競りの結果',
      'auc.none': '何も買わなかった',
      'auc.got': '{name} ×{n}人前（{price}文）',
      'auc.done': '仕入れ先を選ぶ画面へ',

      // ---------- 夜：営業 ----------
      'night.open': '開店！',
      'night.close': '閉店まで {n}秒',
      'night.closing': 'もうすぐ閉店',
      'night.closed': '閉店！',
      'night.tab.skin': '皮',
      'night.tab.main': '具',
      'night.tab.salsa': 'サルサ',
      'night.tab.herb': '薬味',
      'night.wrap': '包んで出す！',
      'night.clear': 'やり直す',
      'night.needSkin': 'まず「皮」を置こう',
      'night.full': 'もうのせられない',
      'night.out': '在庫がない！',
      'night.noGuest': 'お客さんを待とう',
      'night.pickGuest': '出す相手をタップで選べるよ',
      'night.order': '「{name}」ください！',
      'night.omakase': 'おまかせで！',
      'night.served': '{name}',
      'night.omakaseName': 'おまかせタコス',

      // ---------- 客 ----------
      'cust.chonin': '町人',
      'cust.shokunin': '職人',
      'cust.samurai': 'お侍',
      'cust.chonin.hello': 'ちょいと急いでんだ！|腹へった！はやいとこ頼むよ|へい、ごめんよ',
      'cust.shokunin.hello': '辛いやつ、あるかい？|仕事あがりだ、ひとつ頼む|ぴりっとしたのを頼むぜ',
      'cust.samurai.hello': 'ひとつ所望いたす|見目うるわしきものを頼む|縁起のよいものはあるか',
      'cust.chonin.3': 'はやい！うまい！こりゃいいや！|うんめえ！また来らぁ！',
      'cust.chonin.2': 'うん、悪かねえ|まあまあだな',
      'cust.chonin.1': 'なんでえこりゃ…|ちょいと違うなあ',
      'cust.shokunin.3': 'かーっ！効くねえ！|辛え！うめえ！最高だ！',
      'cust.shokunin.2': 'うまいが、もっと辛くてもいいぜ|悪くねえ',
      'cust.shokunin.1': 'こいつは物足りねえ…|頼んだのと違うぜ',
      'cust.samurai.3': 'なんと見事な…！感服いたした|紅白とはめでたい！',
      'cust.samurai.2': 'うむ、よい味である|悪くない',
      'cust.samurai.1': 'これは…所望したものではない|む…',
      'cust.angry': 'もう待てねえ！|遅い！帰る！|いつまで待たせるんだ！',

      // ---------- 結果 ----------
      'res.title': '{n}日目　本日の売上',
      'res.sales': '売上',
      'res.served': 'お客さん',
      'res.servedVal': '{n}人（怒って帰った人 {a}人）',
      'res.stars': '平均の星',
      'res.satisfaction': '満足度',
      'res.rep': '評判',
      'res.best': '看板タコス',
      'res.bestNone': '—',
      'res.money': '所持金',
      'res.share': '𝕏 でシェア',
      'res.next': '次の日へ',
      'share.text': '江戸の屋台「多幸寿」{day}日目の売上は{sales}文！看板は「{taco}」🌮 #OhEdoTacoTuesday #多幸寿',

      // ---------- ポン吉のひとこと ----------
      'pon.name': 'ポン吉',
      'pon.morning1': 'おはよう、マテオ！まずは魚河岸で魚を競り落とそう！',
      'pon.morningLow': 'トルティーヤが残り少ないよ…大事に使おうね',
      'pon.night1': 'お客さんの注文を見て、皮→具→サルサ→薬味の順にのせて「包んで出す」！',
      'pon.nightTip': '注文にない薬味を足すと、好みしだいで喜ばれるかも',

      // ---------- 食材 ----------
      'ing.tortilla': 'トルティーヤ',
      'ing.tai': '鯛',
      'ing.kisu_ten': '鱚の天ぷら',
      'ing.tako': '茹で蛸',
      'ing.katsuo': '鰹のたたき',
      'ing.shiraae': '白和え衣',
      'ing.sumiso': '酢味噌',
      'ing.bainiku': '梅肉',
      'ing.irizake': '煎り酒',
      'ing.daikon': '大根の千切り',
      'ing.kyuri': '胡瓜',
      'ing.myoga': '茗荷',
      'ing.negi': '葱',
      'ing.yuzu': '柚子',
      'ing.shichimi': '七味',

      // 競りの魚
      'fish.tai': '鯛',
      'fish.kisu': '鱚',
      'fish.tako': '蛸',
      'fish.katsuo': '鰹',

      // ---------- タコス ----------
      'taco.tempura': '江戸前天ぷらタコス',
      'taco.takotaco': '蛸のタコス',
      'taco.kohaku': '紅白めでタコス'
    },

    en: {
      'title.logo': 'Oh!Edo Taco Tuesday!!',
      'title.sub': 'TAKOSU',
      'title.tagline': 'Run a taco stall in old Edo.',
      'title.start': 'Start',
      'title.continue': 'Continue (Day {day})',
      'title.newgame': 'New game',
      'title.resetConfirm': 'Delete your save and start over?',
      'title.by': '🦝 Tanuki Box',

      'ui.day': 'Day {n}',
      'ui.money': '{n} mon',
      'ui.rep': 'Rep {n}',
      'ui.soundOn': '🔊 Sound on',
      'ui.soundOff': '🔇 Sound off',
      'ui.lang': '日本語',
      'ui.ok': 'OK',
      'ui.yes': 'Yes',
      'ui.no': 'No',
      'ui.back': 'Back',
      'ui.stock': 'x{n}',
      'ui.mon': 'mon',

      'morning.title': 'Morning: Shopping',
      'morning.lead': 'Where will you shop today?',
      'morning.left': '{n} more trips today (mini-games)',
      'morning.soon': 'Coming soon',
      'morning.done': 'No more trips today',
      'morning.toNight': 'Finish prep and open for the night',
      'morning.stockTitle': 'Pantry',
      'morning.kind.game': 'Mini-game',
      'morning.kind.shop': 'Shop',

      'sup.uogashi': 'Fish Market',
      'sup.uogashi.desc': 'Morning auction: sea bream, whiting, octopus, bonito',
      'sup.ipponzuri': 'Edo Bay Fishing',
      'sup.ipponzuri.desc': 'Horse mackerel, sardine, tuna, eel',
      'sup.satoyama': 'Paddies & Hills',
      'sup.satoyama.desc': 'Locusts, bee larvae, sansho, water bamboo',
      'sup.yama': 'Mountain Drive',
      'sup.yama.desc': 'Boar, deer',
      'sup.aomono': 'Green Market',
      'sup.aomono.desc': 'Daikon, scallion, myoga, cucumber…',
      'sup.tofuya': 'Tofu Shop',
      'sup.tofuya.desc': 'Tofu, fried tofu',
      'sup.toriya': 'Poultry Shop',
      'sup.toriya.desc': 'Gamecock, duck, eggs',
      'sup.momonjiya': 'Momonjiya',
      'sup.momonjiya.desc': 'Boar and deer (sold as "medicine")',
      'sup.yagenbori': 'Yagenbori Spices',
      'sup.yagenbori.desc': 'Shichimi, chili',
      'sup.komeya': 'Rice Shop',
      'sup.komeya.desc': 'Rice, wheat & buckwheat flour, nori, vinegar',
      'sup.nagasaki': 'Nagasaki Smugglers',
      'sup.nagasaki.desc': 'Secret night deals',

      'auc.title': 'Fish Market Auction',
      'auc.howto': 'The price tag goes up and down. Tap when it looks cheap to win the bid!',
      'auc.start': 'Start the auction',
      'auc.market': 'Usual {n} mon',
      'auc.portions': '{n} servings',
      'auc.tap': 'Tap to bid!',
      'auc.won': 'Sold to you! {n} mon',
      'auc.lost': 'Another buyer got it…',
      'auc.poor': 'Not enough money!',
      'auc.cheap': 'Cheap!',
      'auc.pricey': 'Pricey…',
      'auc.timeLeft': '{n}s left',
      'auc.result': 'Auction results',
      'auc.none': 'You bought nothing',
      'auc.got': '{name} x{n} servings ({price} mon)',
      'auc.done': 'Back to the map',

      'night.open': 'Open!',
      'night.close': 'Closing in {n}s',
      'night.closing': 'Last orders',
      'night.closed': 'Closed!',
      'night.tab.skin': 'Shell',
      'night.tab.main': 'Filling',
      'night.tab.salsa': 'Salsa',
      'night.tab.herb': 'Garnish',
      'night.wrap': 'Wrap & serve!',
      'night.clear': 'Start over',
      'night.needSkin': 'Lay down a shell first',
      'night.full': 'No room for more',
      'night.out': 'Out of stock!',
      'night.noGuest': 'Wait for a customer',
      'night.pickGuest': 'Tap a customer to choose who gets it',
      'night.order': '"{name}", please!',
      'night.omakase': "Chef's choice!",
      'night.served': '{name}',
      'night.omakaseName': "Chef's Choice Taco",

      'cust.chonin': 'Townsman',
      'cust.shokunin': 'Craftsman',
      'cust.samurai': 'Samurai',
      'cust.chonin.hello': "I'm in a hurry!|Starving! Quick, please|Hey there!",
      'cust.shokunin.hello': 'Got anything spicy?|Done with work. One, please|Something with a kick!',
      'cust.samurai.hello': 'I shall have one.|Something pleasing to the eye.|Anything auspicious?',
      'cust.chonin.3': "Fast and tasty! Love it!|Delicious! I'll be back!",
      'cust.chonin.2': 'Not bad.|Pretty good.',
      'cust.chonin.1': "What's this…|Not quite right.",
      'cust.shokunin.3': 'Whoa, that kick! Perfect!|Hot! Tasty! The best!',
      'cust.shokunin.2': 'Good, but it could be hotter.|Not bad.',
      'cust.shokunin.1': "Needs more punch…|That's not what I ordered.",
      'cust.samurai.3': 'Magnificent! I am impressed.|Red and white — how auspicious!',
      'cust.samurai.2': 'A fine flavor.|Not bad.',
      'cust.samurai.1': 'This is not what I asked for.|Hmm…',
      'cust.angry': "I can't wait any longer!|Too slow! I'm leaving!|How long will this take?!",

      'res.title': 'Day {n}: Tonight’s takings',
      'res.sales': 'Sales',
      'res.served': 'Customers',
      'res.servedVal': '{n} (left angry: {a})',
      'res.stars': 'Average stars',
      'res.satisfaction': 'Satisfaction',
      'res.rep': 'Reputation',
      'res.best': 'Best seller',
      'res.bestNone': '—',
      'res.money': 'Purse',
      'res.share': 'Share on 𝕏',
      'res.next': 'Next day',
      'share.text': 'My Edo taco stall "Takosu" made {sales} mon on day {day}! Best seller: "{taco}" 🌮 #OhEdoTacoTuesday',

      'pon.name': 'Ponkichi',
      'pon.morning1': 'Morning, Mateo! Let’s win some fish at the market auction!',
      'pon.morningLow': 'We’re running low on tortillas… use them wisely!',
      'pon.night1': 'Read the order, then add shell → filling → salsa → garnish and tap “Wrap & serve”!',
      'pon.nightTip': 'Extra garnish might make them happier — if it suits their taste.',

      'ing.tortilla': 'Tortilla',
      'ing.tai': 'Sea bream',
      'ing.kisu_ten': 'Whiting tempura',
      'ing.tako': 'Boiled octopus',
      'ing.katsuo': 'Seared bonito',
      'ing.shiraae': 'Tofu cream',
      'ing.sumiso': 'Vinegar miso',
      'ing.bainiku': 'Plum paste',
      'ing.irizake': 'Irizake sauce',
      'ing.daikon': 'Shredded daikon',
      'ing.kyuri': 'Cucumber',
      'ing.myoga': 'Myoga ginger',
      'ing.negi': 'Scallion',
      'ing.yuzu': 'Yuzu',
      'ing.shichimi': 'Shichimi',

      'fish.tai': 'Sea bream',
      'fish.kisu': 'Whiting',
      'fish.tako': 'Octopus',
      'fish.katsuo': 'Bonito',

      'taco.tempura': 'Edo Tempura Taco',
      'taco.takotaco': 'Octopus Taco',
      'taco.kohaku': 'Red & White Lucky Taco'
    }
  };
})(window);
